### PR TITLE
Fixed #703

### LINKED ISSUE #703: Defining two classes with the same name, crashes the game.
Should be a compile error, but it compiles once, and crashes the next time you click compile/OK.

Changing `false` to `true` on [line 497 CBotClass.cpp](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L497)  fixes this issue.

The only place this value is tested, is just above that on [line 474](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L474).

### PR DESCRIPTION
**Pull request by piotrwalkusz1**
Ok, now I will be sending commits one by one.

This fixes #703 issue.

### CODE REVIEW

File: src/CBot/CBotProgram.h [hunk 1]
```diff
@@ -334,6 +334,12 @@ class CBotProgram
     const std::list<CBotFunction*>& GetFunctions();
 
     /**
+     * \brief Check if class with that name exists (public or local)
```
Comment (krzys-h) [inline src/CBot/CBotProgram.h]: This explanation is ambiguous, it sounds like this function will check both private classes in this program and the global list of public classes, which is not the case.

**Comment by krzys-h** [comment]
@melex750 any thoughts?

**Comment by melex750** [comment]
Looks good to me :)
