### PR TITLE
Saved game bug fix

### LINKED ISSUE #672: Keyword 'this' sometimes points to the wrong bot
~~I don't think this is a bug but 
it is not documented in the game.~~
Public functions must be defined preceding a function that is passed
to a bot with `object.factory()`...
please review the following:

``` c++
public void object::ThisIsBetter() {} // <---probably the best place for a public function.

extern void object::Bot#1Main() //-----------------------Bot #1 Main------
{
    if (this.category == WheeledGrabber)
        botfactory.factory(WingedShooter, "Bot#2Main");
}

public void object::ThisWorks()
{
    message( "" + this.category );//      this. refernces Bot #2 when called by #2  
}

public void object::Bot#2Main() //-------------------------Bot #2 Main------
{
    ThisWorks();     //------Output is WingedShooter

    ThisIsBad();     //------Output is WheeledGrabber
}

public void object::ThisIsBad()
{
    message( "" + this.category ); //    this. refernces Bot #1 when called by #2
}
```

### PR DESCRIPTION
**Pull request by melex750**
Fixes #672, #812, #1006, #1026

### CODE REVIEW

File: src/level/player_profile.cpp [hunk 1]
```diff
@@ -518,6 +518,8 @@ void CPlayerProfile::LoadScene(std::string dir)
     CLevelParserLine* line = levelParser.Get("Mission");
     cat = GetLevelCategoryFromDir(line->GetParam("base")->AsString());
 
+	if (dir == "../../crashsave") LoadFinishedLevels(cat);
```
Comment (krzys-h) [inline src/level/player_profile.cpp]: Looks like a bit of an ugly hack, but will work for now.
